### ISSUE TITLE
Mcrypt moved out of core into PECL in PHP 7.2

### ISSUE THREAD

**Issue by gabor-udvari** [debops/ansible-php#43]
Mcrypt [was moved](https://secure.php.net/manual/en/migration72.other-changes.php#migration72.other-changes.mcrypt) out of core into PECL in PHP 7.2, this will brake installation with the default `php__base_packages`, as there is no php7.2-mcrypt:

```
The following packages have unmet dependencies:
 php-mcrypt : Depends: php7.2-mcrypt but it is not installable
E: Unable to correct problems, you have held broken packages.
```

The solution could be making mcrypt a conditional list entry, or there could be a more robust deprecated mapping just like `php__release_included_map`.

**Comment by drybjed** [comment]
Thanks for the heads up. The `php__release_included_map` is more based on the OS release than PHP release, and since this is a change in a specific PHP release, conditional list entry sounds better to me. If there are more changes like this further in the future, then we could look into more extensible solution.

Do you want to try and make a fix? If yes, please do it against the [`debops/debops`](https://github.com/debops/debops/) repository, project development is currently done there.
